---
#
# Ansible managed
#
repository:
  description: Enables the PowerTools/CodeReady Builder (CRB) repository on CentOS Stream, Rocky Linux and AlmaLinux
  homepage: https://mullholland.net
  topics: development, packaging, system, ansible, molecule, playbook
