---
- name: powertools | Check enabled repositories
  ansible.builtin.command:
    cmd: dnf repolist --enabled
  register: repository_powertools_enabled_repos
  changed_when: false

- name: "powertools | Enable repository: {{ repository_powertools_repo_id[ansible_facts['distribution_major_version']] }}"
  ansible.builtin.command:
    cmd: "dnf config-manager --set-enabled {{ repository_powertools_repo_id[ansible_facts['distribution_major_version']] }}"
  when: repository_powertools_repo_id[ansible_facts['distribution_major_version']] not in repository_powertools_enabled_repos.stdout
  changed_when: true
