---
molecule_exceptions:
  - variation: "ubuntu*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "debian*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "fedora*"
    reason: "repo only supports RedHat/CentOS Server"
molecule_scenarios:
  - scenario: "default"
    ansible: ["2.10", "2.11", "2.12"]
    platforms:
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
#  - scenario: "alternative"
#    ansible: ["2.9", "2.10", "2.11"]
#    platforms: ["ubuntu1604", "ubuntu1804", "ubuntu2004", "centos7", "centos8"]
