---
molecule_exceptions:
  - variation: "Ubuntu*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Debian*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Fedora*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "CentOS7"
    reason: "repo does not exists on CentOS 7"
  - variation: "Ubi8"
    reason: "repo does not exists on Ubi 8"
  - variation: "centos-stream9"
    reason: "repo does not exists on CentOS-Stream9"
  - variation: "Amazonlinux"
    reason: "repo does not exists on Amazonlinux"
molecule_scenarios:
  - scenario: "default"
    ansible: ["2.10", "2.11", "2.12"]
    platforms:
      - "centos-stream8"
      - "rockylinux8"
      - "almalinux8"
#  - scenario: "alternative"
#    ansible: ["2.9", "2.10", "2.11"]
#    platforms: ["ubuntu1604", "ubuntu1804", "ubuntu2004", "centos7", "centos8"]
