---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    repository_powertools_repo_id:
      "8": powertools
      "9": crb
      "10": crb

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_version }}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"

    - name: "Check repository is enabled: {{ repository_powertools_repo_id[ansible_facts['distribution_major_version']] }}"
      ansible.builtin.command:
        cmd: dnf repolist --enabled
      register: molecule_repository
      changed_when: false
      failed_when: repository_powertools_repo_id[ansible_facts['distribution_major_version']] not in molecule_repository.stdout

    - name: Check package is installable from repository
      ansible.builtin.dnf:
        name: "libcmocka-devel"
        state: present
      register: package_installed
