---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_repo_file:
      EL:
        "7": "CentOS-Linux-PowerTools.repo"
        "8": "CentOS-Stream-PowerTools.repo"
      CentOS:
        "7": "CentOS-Linux-PowerTools.repo"
        "8": "CentOS-Stream-PowerTools.repo"
        "9": "CentOS-Stream-PowerTools.repo"
      Rocky:
        "8": "CentOS-Stream-PowerTools.repo"
      AlmaLinux:
        "8": "CentOS-Stream-PowerTools.repo"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test if repository exists and is enabled
      lineinfile:
        name: '/etc/yum.repos.d/{{ molecule_repo_file[ansible_distribution][ansible_distribution_major_version] }}'
        line: 'enabled = 1'
        state: present
      check_mode: true
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)

    - name: Check package is installable from repository
      ansible.builtin.yum:
        name: "python3-scons"
        state: present
      register: package_installed
